/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adproc;

/**
 *
 * @author chris
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    boolean check = false;
    float height, length, width, blank;
    double run, finalTotal;
    int quantity, grade, colour;
    boolean top, corner, bottom;
    private ArrayList<Double> orderTotal = new ArrayList<Double>();
    private ArrayList<Box> boxList = new ArrayList<Box>();
    String total, orders;

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        lengthBox = new javax.swing.JTextField();
        heightBox = new javax.swing.JTextField();
        widthBox = new javax.swing.JTextField();
        gradeBox = new javax.swing.JComboBox<>();
        colourPrint = new javax.swing.JComboBox<>();
        quantityBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        costBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        bottomReinf = new javax.swing.JCheckBox();
        cornerReinf = new javax.swing.JCheckBox();
        sealBox = new javax.swing.JCheckBox();
        whlError = new javax.swing.JLabel();
        gradeError = new javax.swing.JLabel();
        colourError = new javax.swing.JLabel();
        quantityError = new javax.swing.JLabel();
        helpButton = new javax.swing.JButton();
        orderCost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        orderButton = new javax.swing.JButton();

        label1.setText("label1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 180, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label2.setText("FlexBox");

        lengthBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lengthBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lengthBox.setText("length");
        lengthBox.setToolTipText("length");
        lengthBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthBoxActionPerformed(evt);
            }
        });
        lengthBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lengthBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lengthBoxKeyTyped(evt);
            }
        });

        heightBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        heightBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        heightBox.setText("height");
        heightBox.setToolTipText("height");
        heightBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                heightBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                heightBoxKeyTyped(evt);
            }
        });

        widthBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        widthBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        widthBox.setText("width");
        widthBox.setToolTipText("width");
        widthBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                widthBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                widthBoxKeyTyped(evt);
            }
        });

        gradeBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        gradeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5" }));
        gradeBox.setToolTipText("Box Grade");
        gradeBox.setName("Grade"); // NOI18N
        gradeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeBoxActionPerformed(evt);
            }
        });

        colourPrint.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        colourPrint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "No Colour", "1 Colour", "2 Colours" }));
        colourPrint.setToolTipText("Do you need colour printing?");
        colourPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourPrintActionPerformed(evt);
            }
        });

        quantityBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        quantityBox.setText("Quantity");
        quantityBox.setToolTipText("Enter the quantity of boxes you require");
        quantityBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityBoxKeyTyped(evt);
            }
        });

        jLabel1.setText("Please enter the width, length and height:");

        jLabel2.setText("Cardboard grade:");

        jLabel3.setText("Colour Printing?");

        jLabel7.setText("Quantity:");

        costBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        costBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costBoxActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("This quote:");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        bottomReinf.setText("Bottom Reinforcement?");
        bottomReinf.setToolTipText("Bottom Reinforcement?");
        bottomReinf.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        cornerReinf.setText("Corner Reinforcement?");
        cornerReinf.setToolTipText("Corner Reinforcement?");
        cornerReinf.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        sealBox.setText("Sealable Top?");
        sealBox.setToolTipText("Sealable Top?");
        sealBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        whlError.setForeground(new java.awt.Color(255, 0, 0));
        whlError.setText("  ");

        gradeError.setForeground(new java.awt.Color(255, 0, 0));
        gradeError.setText(" ");

        colourError.setForeground(new java.awt.Color(255, 0, 0));
        colourError.setText(" ");

        quantityError.setForeground(new java.awt.Color(255, 0, 0));
        quantityError.setText(" ");

        helpButton.setText("Help");
        helpButton.setToolTipText("Help Section");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        orderCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCostActionPerformed(evt);
            }
        });

        jLabel4.setText("Total order quote:");

        orderButton.setText("Total");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpButton)
                .addGap(21, 21, 21)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(quantityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderCost, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colourError)
                            .addComponent(gradeError)
                            .addComponent(whlError)
                            .addComponent(sealBox)
                            .addComponent(cornerReinf)
                            .addComponent(bottomReinf)
                            .addComponent(gradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(widthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lengthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heightBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(colourPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(quantityError))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton)
                    .addComponent(helpButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(whlError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(gradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gradeError)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colourPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colourError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottomReinf)
                .addGap(18, 18, 18)
                .addComponent(cornerReinf)
                .addGap(18, 18, 18)
                .addComponent(sealBox)
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityError)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(submitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(orderButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        quantityBox.setText("Quantity");
        lengthBox.setText("length");
        heightBox.setText("height");
        widthBox.setText("width");
        costBox.setText(" ");
        orderCost.setText(" ");
        orderTotal.clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void gradeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeBoxActionPerformed
        if (gradeBox.getSelectedIndex() != 0) {
            gradeError.setText(" ");
        }
    }//GEN-LAST:event_gradeBoxActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (canFloat(widthBox.getText()) == false) {
            whlError.setText("Please enter a value for width");
            widthBox.setForeground(Color.red);
        } else if (Float.parseFloat(widthBox.getText()) < 1) {
            whlError.setText("Value for height must be greater than 1");
            widthBox.setForeground(Color.red);
        } else if (canFloat(lengthBox.getText()) == false) {
            whlError.setText("Please enter a value for length");
            lengthBox.setForeground(Color.red);
        } else if (Float.parseFloat(lengthBox.getText()) < 1) {
            whlError.setText("Value for height must be greater than 1");
            lengthBox.setForeground(Color.red);
        } else if (canFloat(heightBox.getText()) == false) {
            whlError.setText("Please enter a value for height");
            heightBox.setForeground(Color.red);
        } else if (Float.parseFloat(heightBox.getText()) < 1) {
            whlError.setText("Value for height must be greater than 1");
            heightBox.setForeground(Color.red);
        } else if (gradeBox.getSelectedIndex() == 0) {
            gradeError.setText("Please choose an option for grade");
        } else if (colourPrint.getSelectedIndex() == 0) {
            colourError.setText("Please choose an option for colour printing");
        } else if (canFloat(quantityBox.getText()) == false) {
            quantityError.setText("Quantity: between 1 and 100");
            quantityBox.setForeground(Color.red);
        } else if (Float.parseFloat(quantityBox.getText()) < 1 || Float.parseFloat(quantityBox.getText()) > 100) {
            quantityError.setText("Quantity: between 1 and 100");
            quantityBox.setForeground(Color.red);
        } else {
            check = true;
        }

        if (check == true) {
            height = Float.parseFloat(heightBox.getText());
            width = Float.parseFloat(widthBox.getText());
            length = Float.parseFloat(lengthBox.getText());
            quantity = Integer.parseInt(quantityBox.getText());
            top = sealBox.isSelected();
            corner = cornerReinf.isSelected();
            bottom = bottomReinf.isSelected();
            for (int i = 0; i <= gradeBox.getSelectedIndex(); i++) {
                grade = i;
            }
            for (int i = 0; i <= colourPrint.getSelectedIndex(); i++) {
                colour = i;
            }
            if (grade >= 1 && grade <= 3 && colour == 1 && corner == false && bottom == false) {
                BoxType1();
            } else if (grade >= 2 && grade <= 4 && colour == 2 && corner == false && bottom == false) {
                BoxType2();
            } else if (grade >= 2 && colour == 3 && corner == false && bottom == false) {
                BoxType3();
            } else if (grade >= 2 && colour == 3 && corner == false && bottom == true) {
                BoxType4();
            } else if (grade >= 3 && colour == 3 && corner == true && bottom == true) {
                BoxType5();
            } else {
                mesbox("This order is not possible");
            }

        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void widthBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_widthBoxKeyTyped

    }//GEN-LAST:event_widthBoxKeyTyped

    private void lengthBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lengthBoxKeyTyped

    }//GEN-LAST:event_lengthBoxKeyTyped

    private void heightBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heightBoxKeyTyped

    }//GEN-LAST:event_heightBoxKeyTyped

    private void quantityBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityBoxKeyTyped

    }//GEN-LAST:event_quantityBoxKeyTyped

    private void colourPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourPrintActionPerformed
        if (colourPrint.getSelectedIndex() != 0) {
            colourError.setText(" ");
        }
    }//GEN-LAST:event_colourPrintActionPerformed

    private void quantityBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityBoxKeyReleased
        if (canFloat(quantityBox.getText())) {
            quantityError.setText(" ");
            quantityBox.setForeground(Color.black);
        }
    }//GEN-LAST:event_quantityBoxKeyReleased

    private void widthBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_widthBoxKeyReleased
        if (canFloat(widthBox.getText())) {
            whlError.setText(" ");
            widthBox.setForeground(Color.black);
        }
    }//GEN-LAST:event_widthBoxKeyReleased

    private void lengthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthBoxActionPerformed

    private void lengthBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lengthBoxKeyReleased
        if (canFloat(lengthBox.getText())) {
            whlError.setText(" ");
            lengthBox.setForeground(Color.black);
        }
    }//GEN-LAST:event_lengthBoxKeyReleased

    private void heightBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heightBoxKeyReleased
        if (canFloat(heightBox.getText())) {
            whlError.setText(" ");
            heightBox.setForeground(Color.black);
        }
    }//GEN-LAST:event_heightBoxKeyReleased

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        mesbox("Type 1 box: Grade 1-3, no colours, no corner/bottom reinforcement \n"
                + "Type 2 box: Grade 2-4, one colour, no corner/bottom reinforcement \n"
                + "Type 3 box: Grade 2-5, 2 colours, no corner/bottom reinforcement \n"
                + "Type 4 box: Grade 2-5, 2 colours, bottom reinforcement \n"
                + "Type 5 box: Grade 3-5, 2 colours, corner and bottom reinforcement \n"
                + "All combinations can have sealable tops"
        );
        
    }//GEN-LAST:event_helpButtonActionPerformed

    private void orderCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderCostActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        finalTotal = 0;
        for(int i = 0; i < orderTotal.size(); i++){
            finalTotal += orderTotal.get(i);
        }
        finalTotal = Math.round(finalTotal * 100.00)/100.00;
        String totalText = Double.toString(finalTotal);
        orderCost.setText("£" + totalText);
        for(int i = 0; i < boxList.size(); i++){
           System.out.println(boxList.get(i).grade);
           System.out.println(boxList.get(i).quantity);
        }
        
    }//GEN-LAST:event_orderButtonActionPerformed

    private void costBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void mesbox(String s) {
        JOptionPane.showMessageDialog(null, s);
    }

    public static boolean canFloat(String stringNum) {
        try {
            float f = Float.parseFloat(stringNum);

        } catch (NumberFormatException | NullPointerException nfe) {
            return false;
        }
        return true;
    }

    private void BoxType1() {

        Type1 boxType1 = new Type1(height, width, length, grade, quantity, top);
        run = boxType1.calculate(blank);
        total = Double.toString(Math.round(run * 100.00)/100.00);
        costBox.setText("£" + total);
        orderTotal.add(run);
        boxList.add(boxType1);
    }

    private void BoxType2() {

        Type2 boxType2 = new Type2(height, width, length, grade, colour, quantity, top);
        run = boxType2.calculate(blank);
        total = Double.toString(Math.round(run * 100.00)/100.00);
        costBox.setText("£" + total);
        orderTotal.add(run);
        boxList.add(boxType2);
    }

    private void BoxType3() {

        Type3 boxType3 = new Type3(height, width, length, grade, colour, quantity, top);
        run = boxType3.calculate(blank);
        total = Double.toString(Math.round(run * 100.00)/100.00);
        costBox.setText("£" + total);
        orderTotal.add(run);
        boxList.add(boxType3);
    }

    private void BoxType4() {

        Type4 boxType4 = new Type4(height, width, length, grade, colour, quantity, bottom, top);
        run = boxType4.calculate(blank);
        total = Double.toString(Math.round(run * 100.00)/100.00);
        costBox.setText("£" + total);
        orderTotal.add(run);
        boxList.add(boxType4);
    }

    private void BoxType5() {

        Type5 boxType5 = new Type5(height, width, length, grade, colour, quantity, bottom, corner, top);
        run = boxType5.calculate(blank);
        total = Double.toString(Math.round(run * 100.00)/100.00);
        costBox.setText("£" + total);
        orderTotal.add(run);
        boxList.add(boxType5);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bottomReinf;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel colourError;
    private javax.swing.JComboBox<String> colourPrint;
    private javax.swing.JCheckBox cornerReinf;
    private javax.swing.JTextField costBox;
    private javax.swing.JComboBox<String> gradeBox;
    private javax.swing.JLabel gradeError;
    private javax.swing.JTextField heightBox;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField lengthBox;
    private javax.swing.JButton orderButton;
    private javax.swing.JTextField orderCost;
    private javax.swing.JTextField quantityBox;
    private javax.swing.JLabel quantityError;
    private javax.swing.JCheckBox sealBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel whlError;
    private javax.swing.JTextField widthBox;
    // End of variables declaration//GEN-END:variables
}
