/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adproc;

/**
 *
 * @author chris
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public boolean check = false;
    public float height, length, width, blank;
    public double run, finalTotal;
    public int quantity, grade, colour;
    public boolean top, corner, bottom;
    private ArrayList<Double> orderTotal = new ArrayList<Double>(); //stores prices
    private ArrayList<Box> boxList = new ArrayList<Box>(); //stores box objects
    public String total, orders, colourType, cornerChoice, bottomChoice, topChoice;

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        checkBoxes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        whlError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        widthBox = new javax.swing.JTextField();
        lengthBox = new javax.swing.JTextField();
        heightBox = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        gradeBox = new javax.swing.JComboBox<>();
        gradeError = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        colourPrint = new javax.swing.JComboBox<>();
        colourError = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        bottomReinf = new javax.swing.JCheckBox();
        cornerReinf = new javax.swing.JCheckBox();
        sealBox = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        quantityBox = new javax.swing.JTextField();
        quantityError = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        orderCost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        orderButton = new javax.swing.JButton();
        costBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        orderRem = new javax.swing.JTextField();
        removeOrder = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        removeError = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        clearButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();

        label1.setText("label1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 180, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dimensions"));

        whlError.setForeground(new java.awt.Color(255, 0, 0));
        whlError.setText("  ");

        jLabel1.setText("Please enter the width, length and height in mm:");

        widthBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        widthBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        widthBox.setText("width");
        widthBox.setToolTipText("width");
        widthBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                widthBoxMouseClicked(evt);
            }
        });
        widthBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                widthBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                widthBoxKeyTyped(evt);
            }
        });

        lengthBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lengthBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lengthBox.setText("length");
        lengthBox.setToolTipText("length");
        lengthBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lengthBoxMouseClicked(evt);
            }
        });
        lengthBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthBoxActionPerformed(evt);
            }
        });
        lengthBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lengthBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lengthBoxKeyTyped(evt);
            }
        });

        heightBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        heightBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        heightBox.setText("height");
        heightBox.setToolTipText("height");
        heightBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                heightBoxMouseClicked(evt);
            }
        });
        heightBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightBoxActionPerformed(evt);
            }
        });
        heightBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                heightBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                heightBoxKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(widthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lengthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(heightBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(whlError))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lengthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(heightBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(widthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(whlError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cardboard Grade"));

        gradeBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        gradeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5" }));
        gradeBox.setToolTipText("Box Grade");
        gradeBox.setName("Grade"); // NOI18N
        gradeBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gradeBoxMouseEntered(evt);
            }
        });
        gradeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeBoxActionPerformed(evt);
            }
        });

        gradeError.setForeground(new java.awt.Color(255, 0, 0));
        gradeError.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeError))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gradeError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Colour Printing"));

        colourPrint.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        colourPrint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "No Colour", "1 Colour", "2 Colours" }));
        colourPrint.setToolTipText("Do you need colour printing?");
        colourPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colourPrintMouseEntered(evt);
            }
        });
        colourPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourPrintActionPerformed(evt);
            }
        });

        colourError.setForeground(new java.awt.Color(255, 0, 0));
        colourError.setText(" ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colourPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colourError))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colourPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colourError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Extra Features"));

        bottomReinf.setBackground(new java.awt.Color(204, 204, 204));
        bottomReinf.setText("Bottom Reinforcement?");
        bottomReinf.setToolTipText("Bottom Reinforcement?");
        bottomReinf.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        cornerReinf.setBackground(new java.awt.Color(204, 204, 204));
        cornerReinf.setText("Corner Reinforcement?");
        cornerReinf.setToolTipText("Corner Reinforcement?");
        cornerReinf.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        sealBox.setBackground(new java.awt.Color(204, 204, 204));
        sealBox.setText("Sealable Top?");
        sealBox.setToolTipText("Sealable Top?");
        sealBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bottomReinf)
                    .addComponent(cornerReinf)
                    .addComponent(sealBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bottomReinf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cornerReinf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sealBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantity"));

        quantityBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        quantityBox.setText("Quantity");
        quantityBox.setToolTipText("Enter the quantity of boxes you require");
        quantityBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quantityBoxMouseClicked(evt);
            }
        });
        quantityBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityBoxKeyTyped(evt);
            }
        });

        quantityError.setForeground(new java.awt.Color(255, 0, 0));
        quantityError.setText(" ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityError))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quantityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quantityError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Your order:");

        outputArea.setEditable(false);
        outputArea.setColumns(2);
        outputArea.setRows(8);
        jScrollPane1.setViewportView(outputArea);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        orderCost.setEditable(false);
        orderCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCostActionPerformed(evt);
            }
        });

        jLabel4.setText("Total order quote:");

        orderButton.setText("Total");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        costBox.setEditable(false);
        costBox.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        costBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costBoxActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("This quote:");

        submitButton.setText("Get Quote");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitButtonMouseEntered(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderCost, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(submitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(orderButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));

        orderRem.setBackground(new java.awt.Color(240, 240, 240));

        removeOrder.setText("Remove");
        removeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeOrderActionPerformed(evt);
            }
        });

        jLabel2.setText("Remove order:");

        removeError.setText(" ");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeError)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(removeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderRem, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeOrder)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeError)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));

        label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label2.setText("FlexBox");

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.setToolTipText("Help Section");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clearButton)
                        .addComponent(closeButton)
                        .addComponent(helpButton))
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        quantityBox.setText("Quantity"); //this button resets all input/output textboxes
        lengthBox.setText("length");
        heightBox.setText("height");
        widthBox.setText("width");
        bottomReinf.setSelected(false);
        cornerReinf.setSelected(false);
        sealBox.setSelected(false);
        costBox.setText(" ");
        orderCost.setText(" ");
        orderTotal.clear();
        outputArea.setText(null);
        boxList.clear();
        orderTotal.clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void gradeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeBoxActionPerformed
        verifyGrade();
    }//GEN-LAST:event_gradeBoxActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (canFloat(widthBox.getText()) == false || Float.parseFloat(widthBox.getText()) < 100 
                || Float.parseFloat(widthBox.getText()) > 1000 || canFloat(lengthBox.getText()) == false //if value is parsable as a float
                || Float.parseFloat(lengthBox.getText()) < 100 || Float.parseFloat(lengthBox.getText()) > 1000
                || canFloat(heightBox.getText()) == false || Float.parseFloat(heightBox.getText()) < 100 
                || Float.parseFloat(heightBox.getText()) > 1000 || gradeBox.getSelectedIndex() == 0
                || colourPrint.getSelectedIndex() == 0 || canFloat(quantityBox.getText()) == false
                || Float.parseFloat(quantityBox.getText()) < 1 || Float.parseFloat(quantityBox.getText()) > 100) {
            check = false;
        } else {
            check = true;//this variable is used so box type objects can be intialised without errors
        }
        

        if (check == true) {
            height = Float.parseFloat(heightBox.getText());
            width = Float.parseFloat(widthBox.getText());
            length = Float.parseFloat(lengthBox.getText());
            quantity = Integer.parseInt(quantityBox.getText());
            top = sealBox.isSelected();
            corner = cornerReinf.isSelected();
            bottom = bottomReinf.isSelected();
            for (int i = 0; i <= gradeBox.getSelectedIndex(); i++) {
                grade = i;
            }
            for (int i = 0; i <= colourPrint.getSelectedIndex(); i++) {
                colour = i;
            }
            if (grade >= 1 && grade <= 3 && colour == 1 && corner == false && bottom == false) {
                BoxType1();
            } else if (grade >= 2 && grade <= 4 && colour == 2 && corner == false && bottom == false) {
                BoxType2();
            } else if (grade >= 2 && colour == 3 && corner == false && bottom == false) {
                BoxType3();
            } else if (grade >= 2 && colour == 3 && corner == false && bottom == true) {
                BoxType4();
            } else if (grade >= 3 && colour == 3 && corner == true && bottom == true) {
                BoxType5();
            } else {
                mesbox("This order is not possible");
            }

        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void widthBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_widthBoxKeyTyped

    }//GEN-LAST:event_widthBoxKeyTyped

    private void lengthBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lengthBoxKeyTyped

    }//GEN-LAST:event_lengthBoxKeyTyped

    private void heightBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heightBoxKeyTyped

    }//GEN-LAST:event_heightBoxKeyTyped

    private void quantityBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityBoxKeyTyped

    }//GEN-LAST:event_quantityBoxKeyTyped

    private void colourPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourPrintActionPerformed
        verifyColour();
    }//GEN-LAST:event_colourPrintActionPerformed

    private void quantityBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityBoxKeyReleased
       verifyQuantity();
    }//GEN-LAST:event_quantityBoxKeyReleased

    private void widthBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_widthBoxKeyReleased
        verifyWidth();
    }//GEN-LAST:event_widthBoxKeyReleased

    private void lengthBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthBoxActionPerformed

    private void lengthBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lengthBoxKeyReleased
        verifyLength();
    }//GEN-LAST:event_lengthBoxKeyReleased

    private void heightBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heightBoxKeyReleased
        verifyHeight();
    }//GEN-LAST:event_heightBoxKeyReleased

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        mesbox("Type 1 box: Grade 1-3, no colours, no corner/bottom reinforcement \n"// help section
                + "Type 2 box: Grade 2-4, one colour, no corner/bottom reinforcement \n"
                + "Type 3 box: Grade 2-5, 2 colours, no corner/bottom reinforcement \n"
                + "Type 4 box: Grade 2-5, 2 colours, bottom reinforcement \n"
                + "Type 5 box: Grade 3-5, 2 colours, corner and bottom reinforcement \n"
                + "All combinations can have sealable tops"
        );

    }//GEN-LAST:event_helpButtonActionPerformed

    private void orderCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderCostActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        outputArea.setText("");
        finalTotal = 0;//reset combined value of arraylist items
        for (int i = 0; i < orderTotal.size(); i++) {
            finalTotal += orderTotal.get(i);//get combined total of order in arraylist
            displayOrders(i, orderTotal.get(i));//method to write orders on the GUI
        }
        finalTotal = Math.round(finalTotal * 100.00) / 100.00;//formatting total
        String totalText = Double.toString(finalTotal);
        orderCost.setText("£" + totalText);//displaying cost on GUI  
    }//GEN-LAST:event_orderButtonActionPerformed
    private void displayOrders(int orderIndex, double priceIndex) {

        int boxColour = boxList.get(orderIndex).colour;//getting index of the colour selection
        switch (boxColour) {

            case 1:
                colourType = "No colour";
                break;
            case 2:
                colourType = "1 colour";
                break;
            case 3:
                colourType = "2 colours";
        }

        if (boxList.get(orderIndex).bottom == true) {
            bottomChoice = "Yes";
        } else {
            bottomChoice = "No";
        }

        if (boxList.get(orderIndex).corner == true) {
            cornerChoice = "Yes";
        } else {
            cornerChoice = "No";
        }

        if (boxList.get(orderIndex).top == true) {
            topChoice = "Yes";
        } else {
            topChoice = "No";
        }
        /*quantity = Integer.parseInt(quantityBox.getText());
        top = sealBox.isSelected();
        corner = cornerReinf.isSelected();
        bottom = bottomReinf.isSelected();*/

        outputArea.append("\nOrder " + (orderIndex + 1));//writing values to the GUI
        outputArea.append("\n-------------------------------------------------------------");
        outputArea.append("\nBox height/length/width: " + boxList.get(orderIndex).height + "mm/" + boxList.get(orderIndex).length + "mm/" + boxList.get(orderIndex).width + "mm");
        outputArea.append("\nCardboard grade: " + boxList.get(orderIndex).grade);
        outputArea.append("\nColour printing: " + colourType);
        outputArea.append("\nBottom reinforcement: " + bottomChoice);
        outputArea.append("\nCorner reinforcement: " + cornerChoice);
        outputArea.append("\nSealable top: " + topChoice);
        outputArea.append("\nBox quantity: " + boxList.get(orderIndex).quantity);
        outputArea.append("\n-------------------------------------------------------------");
        outputArea.append("\nOrder total: " + "£" + Math.round(priceIndex * 100.00) / 100.00);
        outputArea.append("\n ");
    }
    private void costBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costBoxActionPerformed

    private void widthBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_widthBoxMouseClicked
        widthBox.setText("");
    }//GEN-LAST:event_widthBoxMouseClicked

    private void lengthBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lengthBoxMouseClicked
        lengthBox.setText("");
    }//GEN-LAST:event_lengthBoxMouseClicked

    private void heightBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightBoxActionPerformed

    private void heightBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_heightBoxMouseClicked
        heightBox.setText("");
    }//GEN-LAST:event_heightBoxMouseClicked

    private void quantityBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quantityBoxMouseClicked
        quantityBox.setText("");
    }//GEN-LAST:event_quantityBoxMouseClicked

    private void gradeBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeBoxMouseEntered

    }//GEN-LAST:event_gradeBoxMouseEntered

    private void colourPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colourPrintMouseEntered
 
    }//GEN-LAST:event_colourPrintMouseEntered

    private void submitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseEntered
        verifyHeight();
        verifyLength();
        verifyWidth();
        verifyColour();
        verifyGrade();
        verifyQuantity();
    }//GEN-LAST:event_submitButtonMouseEntered

    private void removeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeOrderActionPerformed
        String removeOrd = orderRem.getText();
        System.out.println(boxList.size());
        int remIndex = Integer.parseInt(removeOrd);
        
        if(canFloat(removeOrd) == false){
            removeError.setForeground(Color.red);
            removeError.setText("Please enter a number");
        } else if(remIndex >= boxList.size()){
            removeError.setForeground(Color.red);
            removeError.setText("This order could not be found");
        } else {
            boxList.remove(remIndex - 1);
            orderTotal.remove(remIndex - 1);
            mesbox("Order removed, please press 'total' again to update your total order price");
        }
    }//GEN-LAST:event_removeOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void mesbox(String s) {//help box
        JOptionPane.showMessageDialog(null, s);
    }

    public static boolean canFloat(String stringNum) {//checks if a value can be parsed as a float
        try {
            float f = Float.parseFloat(stringNum);

        } catch (NumberFormatException | NullPointerException nfe) {
            return false;
        }
        return true;
    }

    private void BoxType1() {//creates object of box type 1

        Type1 boxType1 = new Type1(height, width, length, grade, quantity, top);
        run = boxType1.calculate(blank);
        total = Double.toString(Math.round(run * 100.00) / 100.00);
        costBox.setText("£" + total);
        orderTotal.add(run);
        boxList.add(boxType1);
    }

    private void BoxType2() {

        Type2 boxType2 = new Type2(height, width, length, grade, colour, quantity, top);
        run = boxType2.calculate(blank);
        total = Double.toString(Math.round(run * 100.00) / 100.00);
        costBox.setText("£" + total);
        orderTotal.add(run);
        boxList.add(boxType2);
    }

    private void BoxType3() {

        Type3 boxType3 = new Type3(height, width, length, grade, colour, quantity, top);
        run = boxType3.calculate(blank);
        total = Double.toString(Math.round(run * 100.00) / 100.00);
        costBox.setText("£" + total);
        orderTotal.add(run);
        boxList.add(boxType3);
    }

    private void BoxType4() {

        Type4 boxType4 = new Type4(height, width, length, grade, colour, quantity, bottom, top);
        run = boxType4.calculate(blank);
        total = Double.toString(Math.round(run * 100.00) / 100.00);
        costBox.setText("£" + total);
        orderTotal.add(run);
        boxList.add(boxType4);
    }

    private void BoxType5() {

        Type5 boxType5 = new Type5(height, width, length, grade, colour, quantity, bottom, corner, top);
        run = boxType5.calculate(blank);
        total = Double.toString(Math.round(run * 100.00) / 100.00);
        costBox.setText("£" + total);
        orderTotal.add(run);
        boxList.add(boxType5);
    }
    
    private void verifyHeight(){
       if (canFloat(heightBox.getText()) == false) {
            whlError.setText("Please enter a value for height");
            heightBox.setForeground(Color.red);
        } else if (Float.parseFloat(heightBox.getText()) < 100) {
            whlError.setText("Value for height must be greater than 100mm");
            heightBox.setForeground(Color.red);
        } else if (Float.parseFloat(heightBox.getText()) > 1000) {
            whlError.setText("Value for height must not be greater than 1 metre");
            heightBox.setForeground(Color.red);
        } else {
            whlError.setText(" ");
            heightBox.setForeground(Color.black);
        }  
    }
    
    private void verifyLength(){
        if (canFloat(lengthBox.getText()) == false) {
            whlError.setText("Please enter a value for length");
            lengthBox.setForeground(Color.red);
        } else if (Float.parseFloat(lengthBox.getText()) < 100) {
            whlError.setText("Value for length must be greater than 100mm");
            lengthBox.setForeground(Color.red);
        } else if (Float.parseFloat(lengthBox.getText()) > 1000) {
            whlError.setText("Value for length must not be greater than 1 metre");
            lengthBox.setForeground(Color.red);
        } else {
            whlError.setText(" ");
            lengthBox.setForeground(Color.black);
        }  
    }
    
    private void verifyWidth(){
        if (canFloat(widthBox.getText()) == false) {
            whlError.setText("Please enter a value for width"); //error message displayed
            widthBox.setForeground(Color.red); //font colour changed to red
        } else if (Float.parseFloat(widthBox.getText()) < 100) {
            whlError.setText("Value for width must be greater than 100mm");//a reasonable starting size for box width
            widthBox.setForeground(Color.red);
        } else if (Float.parseFloat(widthBox.getText()) > 1000) {
            whlError.setText("Value for width must not be greater than 1 metre");//a reasonable starting size for box width
            widthBox.setForeground(Color.red);
        } else {
            whlError.setText(" ");
            widthBox.setForeground(Color.black);
        } 
    }
    
    private void verifyQuantity(){
         if (canFloat(quantityBox.getText()) == false || Float.parseFloat(quantityBox.getText()) < 1 || Float.parseFloat(quantityBox.getText()) > 100) {
            quantityError.setText("Must be a whole number between 1 and 100");
            quantityBox.setForeground(Color.red);
        } else {
            quantityError.setText(" ");
            quantityBox.setForeground(Color.black);
        } 
    }
    
    private void verifyColour(){
        if (colourPrint.getSelectedIndex() == 0) {
            colourError.setText("Please choose an option for colour printing");
        } else {
            colourError.setText(" ");
        }
    }
    
    private void verifyGrade(){
        if (gradeBox.getSelectedIndex() == 0) {//removes error message if value has been selected
            gradeError.setText("Please choose an option for grade");
        } else {
            gradeError.setText(" ");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bottomReinf;
    private javax.swing.ButtonGroup checkBoxes;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel colourError;
    private javax.swing.JComboBox<String> colourPrint;
    private javax.swing.JCheckBox cornerReinf;
    private javax.swing.JTextField costBox;
    private javax.swing.JComboBox<String> gradeBox;
    private javax.swing.JLabel gradeError;
    private javax.swing.JTextField heightBox;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField lengthBox;
    private javax.swing.JButton orderButton;
    private javax.swing.JTextField orderCost;
    private javax.swing.JTextField orderRem;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JTextField quantityBox;
    private javax.swing.JLabel quantityError;
    private javax.swing.JLabel removeError;
    private javax.swing.JButton removeOrder;
    private javax.swing.JCheckBox sealBox;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel whlError;
    private javax.swing.JTextField widthBox;
    // End of variables declaration//GEN-END:variables
}
